### ISSUE TITLE
visualizations of pathways

### ISSUE THREAD

**Issue by timadriaens** [trias-project/indicators#75]
some ideas to visually do more with introduction pathways of alien species in the checklist based on a similar exercise by Van Wilgen & Wilson 2017 (The status of Biological Invasions and their management in South Africa). I know that for TrIAS we have opted for a tabular view but just to show some possibilities for future use - planning to code these graphs for NARA-T see [this issue](https://github.com/inbo/easin/issues/19):

Aantal soorten per pathway (gerangschikt op CBD level1 en level2)
![20200317_160603](https://user-images.githubusercontent.com/16116743/76880758-7108fc80-6878-11ea-8169-c8b34dc3c7d2.jpg)

evolution of pathways in time (based on first introduction date)
![20200317_160612](https://user-images.githubusercontent.com/16116743/76881469-77e43f00-6879-11ea-8bc6-d0c727eee58c.jpg)

![20200317_160633](https://user-images.githubusercontent.com/16116743/76881151-04423200-6879-11ea-91a6-2eb9af1bb606.jpg)

**Comment by damianooldoni** [comment]
We have 32 pathways at level 2, that's way more than the pathways in graph you show, @timadriaens. So, our INBO style graph would result in something like this:
![test_visualize_pathways](https://user-images.githubusercontent.com/33662631/78504324-afedec00-776c-11ea-9d0f-bcf5cca9b49d.png)

Or we should opt for a trade-off and cutting some pathways away. @timadriaens what do you think?

**Comment by damianooldoni** [comment]
By the way, the graph above was a draft of the graph using **ALL** taxa, no lower limit to year of introduction assigned and all kingdoms together.

Here below I show how it would look like for:

### Plantae
![test_visualize_pathways](https://user-images.githubusercontent.com/33662631/78509910-d3775d80-7791-11ea-951c-800f49278d75.png)

### Vertebrates
![test_visualize_pathways](https://user-images.githubusercontent.com/33662631/78509979-4680d400-7792-11ea-9e5b-82d25329c614.png)

### Invertebrates
![test_visualize_pathways](https://user-images.githubusercontent.com/33662631/78509994-687a5680-7792-11ea-821f-f66d9014758d.png)

So, breaking down taxonomically helps tremendously to reduce number of pathways level 2. I think also that removing the "unknown" pathways, especially from pathway level 1, would ease readability (one graph line less). The number of unknowns are still given in the tables.

### Taxa introduced after 1950

Here below how it would like to use only taxa with year of first introduction above 1950 or unknown:
![test_visualize_pathways](https://user-images.githubusercontent.com/33662631/78510207-f99dfd00-7793-11ea-9ddb-290bebd22647.png)

Personally, I find the last one a bad graph as the graph in [previous comment](https://github.com/trias-project/indicators/issues/75#issuecomment-609445265). Too many pathways level 2, not easy to read, This was the reason you and @ToonVanDaele, during the hackathon in Botanic garden Meise on April 16, 2018 decided to opt for tables instead of graphs: see https://github.com/trias-project/indicators/issues/19#issuecomment-381630412.

So, my opinion is: show graphs only when number of pathways level 2 are 10 or less. 
@timadriaens and TrIAS fellas: feedback on the comments above is welcome.

**Comment by peterdesmet** [comment]
Yes, graphs per plants/vertebrates/invertebrates are definitely more readable. I would also rotate the whole chart 90 clockwise, so second level pathways are on y-axis (and more readable), first-level pathways are blocks and numbers are on x-axis

**Comment by damianooldoni** [comment]
This issue can be closed. Functions in trias work. pathways document has been improved. If something more specific needs to be done, a new issue can be written.
